//! \file decayModel.hh
//! \brief Total-decay-curve model (no neutron gates) generated by main.cc
//! (output: decayModel_cal.cc).
//!
//! Two categories fitted simultaneously, both extended and unbinned:
//!   "pos": x = t_beta - t_ion >= startTime  (forward time)
//!          sum over species m of C_m*exp(-l_m*t)  +  bkg*flat
//!   "neg": x = t_beta - t_ion <  0          (backward time)
//!          bkg*flat
//! A beta can only follow its own implant, so every backward-time
//! correlation is an accidental (wrong-ion) one; the backward region
//! therefore measures the accidental rate bkg (counts per second) that is
//! shared with the forward region.
//!
//! C_m are the Bateman partial-fraction coefficients of every decay path
//! that contains exp(-l_m*t), summed. RooRealSumPdf uses each function's
//! RAW integral over the observable range, so bkg is a rate in counts/s
//! on both sides and narrowing x_pos to [startTime,T] needs no extra
//! survival factor.
//!
//! Alpha decay: pa<k> = alpha branching fraction of species k; beta links
//! carry (1-pa<k>), alpha links (Z-2, N-2) pa<k>; a decay of species k is
//! detected with weight (1-pa<k>)+pa<k>*ab (parent: (1-pa0)*be+pa0*ab), ab =
//! alpha/beta detection-efficiency ratio. Only species with an alpha branch
//! get these factors.
//!
//! Caller must supply P containing, by name: l<k>, p1n<k>, p2n<k>, py<k>,
//! pa<k> for k=0..nri-1, N0raw, be, ab, bkg, bkga.

#ifndef decayModel_h
#define decayModel_h 1

#include <RooArgList.h>
#include <RooRealVar.h>
#include <RooAbsPdf.h>
#include <RooAbsReal.h>
#include <RooCategory.h>
#include <RooSimultaneous.h>
#include <vector>

struct DecayModel {
    RooCategory* cat;
    RooSimultaneous* simPdf;
    RooAbsPdf* decayPos;   // forward-time pdf (activity + background)
    RooAbsPdf* bkgNeg;     // backward-time pdf (background only)
    // Total number of beta decays (any neutron multiplicity, all time) of
    // each PHYSICALLY decaying species k; parent (k=0) includes be.
    std::vector<RooAbsReal*> TrueNbetaPerSpecies;
    RooAbsReal* TrueNbeta; // sum over species
    // Components of decayPos, for plotting:
    //   CombinedBkgPos + ActivityPdfParentPos + ActivityPdfDaughtersPos == decayPos
    RooAbsPdf* CombinedBkgPos;
    RooAbsPdf* ActivityPdfParentPos;
    RooAbsPdf* ActivityPdfDaughtersPos;

    // Alpha-gated model, generated only for networks with an alpha branch
    // (nullptr otherwise). Categories of gcat: bpos/bneg = decays not tagged
    // as alpha (forward/backward time), apos/aneg = alpha-tagged decays.
    //   betaPos  = sum_m CB_m exp(-l_m t) + bkg ,  CB: beta-gate weights
    //   alphaPos = sum_m CA_m exp(-l_m t) + bkga,  CA: pa_k*ab
    //   bkgNeg (bkg) and alphaNeg (bkga) in backward time.
    // betaPos+alphaPos == decayPos with bkg -> bkg+bkga (CombinedBkgPosGated).
    // Forward-time activity WITHOUT the background term, for fitting a
    // mixture of implanted species with one shared background:
    // signalPos (total), betaSignalPos/alphaSignalPos (alpha gates; only for
    // networks with an alpha branch, nullptr otherwise).
    RooAbsPdf* signalPos=nullptr;
    RooAbsPdf* betaSignalPos=nullptr;
    RooAbsPdf* alphaSignalPos=nullptr;

    RooCategory* gcat=nullptr;
    RooSimultaneous* simPdfGated=nullptr;
    RooAbsPdf* betaPos=nullptr;
    RooAbsPdf* alphaPos=nullptr;
    RooAbsPdf* alphaNeg=nullptr;
    RooAbsPdf* CombinedBkgPosGated=nullptr;
};

DecayModel* buildDecayModel(RooArgList& P, RooRealVar& x_pos, RooRealVar& x_neg);

// Builders of all networks in this build (one per implanted species; a
// single-species build has just buildDecayModel). Generated by build.sh.
typedef DecayModel* (*DecayModelBuilder)(RooArgList&, RooRealVar&, RooRealVar&);
std::vector<DecayModelBuilder> decayModelBuilders();

#endif
